### ISSUE TITLE
Better Server Name

### ISSUE THREAD

**Issue by joshuaitguy** [Arkoudaphobia/ArkoudaphobiaConfig#21]
I've been getting a lot of feed back that the server name could be better.  This serves as a reminder to my self to do just that, find a better name.

**Comment by CaptainFIST** [comment]
maybe something that incorporates bears? where do black bears famously live kappa

**Comment by joshuaitguy** [comment]
Well Arkoudaphobia is the fear of bears ... but I think I know what you mean :-)

**Comment by joshuaitguy** [comment]
The server has been updated to be named "The Bear Cave"
