### ISSUE TITLE
Figure out why Portals are invisible

### ISSUE THREAD

**Issue by joshuaitguy** [Arkoudaphobia/ArkoudaphobiaConfig#22]
Since the latest update to Rust on 2/25 portals have become invisible.

**Comment by joshuaitguy** [comment]
Well I'm not finding it mentioned on the mod's page on Oxide.  Checking the config file to make sure it's still configured correctly.  If everything checks out there then I'll post a note to the mod's support section.

**Comment by joshuaitguy** [comment]
*Note: because the config file for portals is dynamic it is not tracked in this repository.

**Comment by joshuaitguy** [comment]
I've adjusted the portal hight back to a value of 5 from the set value of 2.  Also moved things around in the config file so that they match more closely with that of the default config file.  I'll log in later and check on things.

**Comment by CaptainFIST** [comment]
If all else fails, maybe placing an object near/under the portals as an indicator for people to know where it is exactly

**Comment by joshuaitguy** [comment]
Opened a request on the mod forum page since my changes had no effect on the visibility of the portals them selfs. http://oxidemod.org/threads/portals.10270/page-18

**Comment by CaptainFIST** [comment]
there was a reply to your comment on the mod page

**Comment by joshuaitguy** [comment]
Yeah, I saw.  I'm going to go digging around the game and see if I can't find the new / correct name of the "FX" and update the mod to use that.

**Comment by joshuaitguy** [comment]
So it appears that the prefab entity's are not stored in files.  So I've selected a smiler  , I hope, prefab entity and written the new value directly to the server to test it.

**Comment by joshuaitguy** [comment]
Ok so assets/bundled/prefabs/fx/smoke_signal_full.prefab is a bad choice ... that one drops my pc to 4 FPS and make the game virtually unplayable.

**Comment by joshuaitguy** [comment]
For now I think I'll settle on using assets/bundled/prefabs/fx/impacts/additive/fire.prefab since it also adds an auditory queue to the remote portals location.
