### ISSUE TITLE
Suggestions for the server

### ISSUE THREAD

**Issue by CaptainFIST** [Arkoudaphobia/ArkoudaphobiaConfig#23]
I'll compile a bullet list for some mods that may help improve the quality of the server, as well as some general advice on how to enhance certain mods already incorporated:

- One of the things that has irked me the most is how little time goes by before a corpse de-spawns, which is why I recommend **Player Corpse Duration Modifier** to tweak settings and find a time a tad longer than 5 minutes (I suggest 15 minutes(gathering it will make them disappear faster)) **has not been updated in a while**

- **CustomLootSpawns** is just a great way to make certain "underrated" spawned buildings better, as well as making large empty areas more of an attraction

- **Cornucopia** is just an all around great mod that changes the entire maps resource geography, making it so that lootboxes/barrels/resource nodes/animals will spawn all over the map instead of being clustered in certain locations. This helps bring balance to the server as people wouldn't have to congregate at certain points to get bp's and die quickly to the gun wielding players. The trade off is it may cause a bit of lag when generating these items (unfortunately the mod removes radtown boxes, i recommend disabling this by setting fixloot to false or there'd be no point to the radtowns) **has not been updated in a while**

- **BetterLoot** adds a whole new layer of customization to looting. Ever looked in a green crate to find a brand spanking new torch in it( ͡° ͜ʖ ͡°)? Very troll-y of you rust... but with this mod, you can just say _to hell_ with torches and other useless materials in lootboxes/barrels! It even lets you tweak the chances to find almost every item in rust, ranking them from common -> very rare **has not been updated in a while**

- **Pills Here** brings usefulness back to anti-rad pills, making them a great source of uncraftable healing. The amount healed can be changed in the config, default is 20 hp

- **Airdrop Extended** helps with various settings in airdrops, one of the most important to me is making the airdrops de-spawn a lot less often so people have some time to chase those suckers down. It also allows for a chance for multiple drops, as well as allowing to change the loot tables in the drops so we don't run for 9 minutes just to get 5 HQ metal and a full outfit of Kanyes clothing line (burlap) **has not been updated in a while**

- **Monument Radiation**? I say YES. If radiation and rad-pills still work properly, this would be an actual use to them, and for hazmat gear for that matter. This mod allows for specific zone selecting for the radiation, so if you wanted you can set an area to be a radiation zone, and incorporate the **CustomLootSpawns** to make the rad zone worth it. Not only will players finally slap on and save those radiation items, but they will probably be met with some resistance from other looters in that area.

- The clusters of resources (metal/sulfur/wood/stone) are too little for people to want to collect them. The base value given is 50, but even with woodcutting at lvl.21 its more worth it to hit a tree a couple times than chasing after these clusters. The mod **GatherManager**, which is already in the server, should have the settings to change the values, i recommend bumping it up a bit to entice people to go gathering more often. I just hate to see certain game mechanics go to waste :+1: 

Any more suggestions I may think of will be posted here

**Comment by joshuaitguy** [comment]
I'm going to close this request and break it into two separate requests.  The first request will be changes I'll target for the next (march) wipe cycle.  The second will be changes I'll target for the next (April) wipe cycle.

**Comment by joshuaitguy** [comment]
Actually, given that some of these may not work I'll break out each one in to its own issue.

**Comment by joshuaitguy** [comment]
Alright, the individual issues have been created.  I'll close this and their progress can be tracked through their individual request.
