### ISSUE TITLE
EventManager

### ISSUE THREAD

**Issue by lostmuted** [Arkoudaphobia/ArkoudaphobiaConfig#8]
figure out why autoevents will not run

**Comment by joshuaitguy** [comment]
Should be fixed in pull request #9

**Comment by joshuaitguy** [comment]
Events still not launching.  This message is provided in console:
[Oxide] 8:49 PM [Info] [Event Manager] No Events were successfully initialized, check that your events are correctly configured in AutoEvents - Config

**Comment by joshuaitguy** [comment]
Issue is still unresolved

**Comment by joshuaitguy** [comment]
Ok, now it's fixed
